trigger:
- test
stages:
- stage : build
  displayName: "Build"
  jobs:
  - job: build
    displayName: "Build"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node js'
    - script: |
        npm install
      displayName: 'npm install'
- stage: TDD
  dependsOn: build
  displayName: "Test TDD"
  jobs:
  - job: test
    displayName: "Test TDD"
    steps:
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: "test"



   
