trigger:
- test
stages:
- stage : buildandtest
  displayName: "Build and test"
  jobs:
  - job: build
    displayName: "Build"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '19.7.0'
      displayName: 'Install Node js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        npm test
      displayName: 'npm test'
#.................Second stage dockerizing app.........
# - stage: TDD
#   dependsOn: build
#   displayName: "Test TDD"
#   jobs:
#   - job: test
#     displayName: "Test TDD"
#     steps:
#     - script: |
#         npm test
#       displayName: 'npm test'


   






# trigger:
# - test

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '19.7.0'
#     #checkLatest: true
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#   displayName: 'npm install'

# - script: |
#     npm test
#   displayName: 'npm test'


