#azure ipelin to deploy my devsu app
trigger:
- test
pool:
  vmImage: 'ubuntu-latest'
variables: 
  ImageName: 'danielmerchan1910/simpleapp'

stages:
# - stage : buildandtest
#   displayName: "Build and test"
#   jobs:
#   - job: build
#     displayName: "Build and test"
#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '19.7.0'
#       displayName: 'Install Node js'
#     - script: |
#         npm install
#       displayName: 'npm install'
#     - script: |
#         npm test
#       displayName: 'npm test'
#.................Second stage dockerizing app.........
# - stage: buildandpush
#   displayName: "Build and push docker"
#   jobs:
#   - job: BuildandPush
#     displayName: Build and push Docker image
#     steps:
#     - task: Docker@2
#       displayName: Login to Docker Hub
#       inputs:
#         command: login
#         containerRegistry: DockerHubConnection
#         displayName: 'Login in docker hub'
#     - task: Docker@2
#       displayName: Build and Push
#       inputs:
#         command: buildAndPush
#         Dockerfile: './Dockerfile'
#         repository: '$(ImageName)'
        # #'--- we can use tag as latest
        # #tags: |
        # #$(tag)
#..............third stage deploy to k8s cluster
- stage: Deploy
  displayName: "Deploy in aks"
 # dependsOn: buildandpush
  jobs:
  - job: deploy
    displayName: Deploy in aks
    steps:
    - task: KubernetesManifest@0
      displayName: Deploy
      inputs:
        action: deploy
        kubernetesServiceConnection: myk8scluster
        namespace: default
        #name of my manifests
        manifests: |
          ./manifests/deployment.yaml  
          ./manifests/ingress.yaml
          ./manifests/lbservice.yaml
        #-------------------------
        #-------------------------
        #name of image from docker
        #containers: |
        #  foo/demo:$(tagVariable1)
        #  bar/demo:$(tagVariable2)
        # imagePullSecrets: |
        #   some-secret
        #   some-other-secret
   









