trigger:
- test

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '19.7.0'
    #checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'


# trigger:
# - test
# stages:
# - stage : build
#   displayName: "Build"
#   jobs:
#   - job: build
#     displayName: "Build"
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '10.x'
#       displayName: 'Install Node js'
#     - script: |
#         npm install
#       displayName: 'npm install'
# - stage: TDD
#   dependsOn: build
#   displayName: "Test TDD"
#   jobs:
#   - job: test
#     displayName: "Test TDD"
#     # steps:
#     # - task: Npm@1
#     #   inputs:
#     #     command: 'custom'
#     #     verbose: true
#     #     workingDir: '/DevsuTestMerhan'
#     #     customCommand: "test"
#     steps:
#     - script: |
#         npm test
#       displayName: 'npm test'


   
