#azure pipeline to deploy my devsu app
trigger:
- test
- main
pool:
  vmImage: 'ubuntu-latest'
variables: 
  ${{ if eq(variables['Build.SourceBranchName'],'main') }}:
    tag: 'main$(Build.BuildId)'
    env: Production
    cluster: myk8scluster   #service connection for main cluster
  ${{ if eq(variables['Build.SourceBranchName'],'test') }}:
    tag: 'test$(Build.BuildId)'
    env: Test
    cluster: myk8scluster   #service connection for test cluster
  ImageName: 'danielmerchan1910/simpleapp'
  containerRegistry: DockerHubConnection
stages:
- stage : buildandtest
  displayName: "Build and test"
  jobs:
  - job: build
    displayName: "Build and test"
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '19.7.0'
      displayName: 'Install Node js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        npm test
      displayName: 'npm test'
#.................Second stage dockerizing app.........
- stage: buildandpush
  displayName: "Build and push docker"
  jobs:
  - job: BuildandPush
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: '$(containerRegistry)'
        displayName: 'Login in docker hub'
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        Dockerfile: './Dockerfile'
        repository: '$(ImageName)'
        tags: |
         $(tag)
#..............third stage deploy to k8s cluster
- stage: Deploy
  displayName: "Deploy in aks"
  dependsOn: buildandpush
  jobs:
  - deployment: prodDeploy
    displayName: Deploy in aks
    environment: $(env)   #configured an approval in this enviroment
    strategy:
      runOnce:
        deploy: 
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Deploytask
            inputs:
              action: deploy
              kubernetesServiceConnection: $(cluster)
              namespace: default
              manifests: |
                ./manifests/deployment.yaml
                ./manifests/ingress.yaml
                ./manifests/lbservice.yaml
              containers: |
                $(ImageName):$(tag)
                
              
              
    # ./manifests/deployment.yaml  
                # ./manifests/ingress.yaml
                # ./manifests/lbservice.yaml







    # - environment: $(env)
    # - job: deploy
    #   #environment: $(env)
    #   displayName: Deploy in aks
    #   steps:
    #   - task: KubernetesManifest@0
    #     displayName: Deploy
    #     inputs:
    #       action: deploy
    #       kubernetesServiceConnection: $(cluster)
    #       namespace: default
    #       manifests: |
    #         ./manifests/deployment.yaml  
    #         ./manifests/ingress.yaml
    #         ./manifests/lbservice.yaml
    #       containers: |
    #         $(ImageName):$(tag)
      
   









